/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Arthania: typeof import('./src/components/arthania/index.vue')['default']
    Formen: typeof import('./src/components/arthania/formen.vue')['default']
    Inventar: typeof import('./src/components/arthania/inventar.vue')['default']
    Klasse: typeof import('./src/components/arthania/klasse.vue')['default']
    Moveset: typeof import('./src/components/arthania/moveset.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ruestung: typeof import('./src/components/arthania/ruestung.vue')['default']
    Stats: typeof import('./src/components/arthania/stats.vue')['default']
  }
}
